"""Seed data for the Operator Training Hub."""
from __future__ import annotations

TRAINING_RESOURCES = [
    {
        "title": "Working Safely Near Autonomous Haul Trucks",
        "description": (
            "Core safety awareness module covering exclusion distances, communication states, "
            "and how to interpret autonomous truck state-visibility signals."
        ),
        "category": "SAFETY",
        "resource_type": "VIDEO",
        "url": "https://training.sentineltwin.local/videos/safe-near-autonomous-trucks",
        "estimated_duration_min": 20,
        "skill_tags": ["proximity-awareness", "autonomous-systems", "exclusion-zones"],
        "machine_type_relevance": ["EXCAVATOR", "LOADER", "DOZER", "GRADER"],
        "is_required": True,
    },
    {
        "title": "Autonomous Truck Operating States: NORMAL, EXCEPTION, RECOVERY and SUSPENDED",
        "description": "Explains each autonomous truck state, what triggers transitions, and what it means for nearby personnel.",
        "category": "SAFETY",
        "resource_type": "PDF_MANUAL",
        "url": "https://training.sentineltwin.local/manuals/truck-states.pdf",
        "estimated_duration_min": 15,
        "skill_tags": ["truck-states", "state-visibility"],
        "machine_type_relevance": ["EXCAVATOR", "LOADER", "DOZER", "GRADER"],
        "is_required": True,
    },
    {
        "title": "Approved Recovery and Isolation Procedure",
        "description": "Step-by-step approved procedure for confirming suspension/isolation before approaching a stopped autonomous truck.",
        "category": "SAFETY",
        "resource_type": "SOP",
        "url": "https://training.sentineltwin.local/sop/recovery-isolation",
        "estimated_duration_min": 25,
        "skill_tags": ["recovery-procedure", "isolation", "lockout"],
        "machine_type_relevance": ["EXCAVATOR", "LOADER", "DOZER", "GRADER"],
        "is_required": True,
    },
    {
        "title": "Loader Blind Spot and Proximity Awareness",
        "description": "Identifies blind spots on loaders/excavators and best practices for proximity awareness on quarry sites.",
        "category": "SAFETY",
        "resource_type": "SIMULATION_GUIDE",
        "url": "https://training.sentineltwin.local/sim/blind-spot",
        "estimated_duration_min": 30,
        "skill_tags": ["blind-spot", "proximity-awareness"],
        "machine_type_relevance": ["LOADER", "EXCAVATOR"],
        "is_required": False,
    },
    {
        "title": "Seatbelt Compliance and Pre-Start Checklist",
        "description": "Pre-start inspection checklist and seatbelt compliance requirements before operating any machine.",
        "category": "COMPLIANCE",
        "resource_type": "CHECKLIST",
        "url": "https://training.sentineltwin.local/checklists/pre-start",
        "estimated_duration_min": 10,
        "skill_tags": ["seatbelt", "pre-start", "compliance"],
        "machine_type_relevance": ["EXCAVATOR", "LOADER", "DOZER", "GRADER"],
        "is_required": True,
    },
    {
        "title": "Fuel-Efficient Loading Cycles",
        "description": "Techniques for reducing idle time and improving load-cycle efficiency without sacrificing safety.",
        "category": "EFFICIENCY",
        "resource_type": "VIDEO",
        "url": "https://training.sentineltwin.local/videos/efficient-loading",
        "estimated_duration_min": 18,
        "skill_tags": ["efficiency", "idling", "fuel-economy"],
        "machine_type_relevance": ["LOADER", "EXCAVATOR"],
        "is_required": False,
    },
    {
        "title": "Fatigue Management and Break Protocol",
        "description": "Guidance on recognizing fatigue signs, scheduled breaks, and when to escalate to a supervisor.",
        "category": "WELLBEING",
        "resource_type": "PDF_MANUAL",
        "url": "https://training.sentineltwin.local/manuals/fatigue-management.pdf",
        "estimated_duration_min": 12,
        "skill_tags": ["fatigue", "breaks", "wellbeing"],
        "machine_type_relevance": ["EXCAVATOR", "LOADER", "DOZER", "GRADER"],
        "is_required": True,
    },
    {
        "title": "Dust, Rain and Low-Visibility Quarry Operations",
        "description": "Operating guidance for maintaining safety and productivity during dust, rain, fog and night operations.",
        "category": "SAFETY",
        "resource_type": "SOP",
        "url": "https://training.sentineltwin.local/sop/low-visibility",
        "estimated_duration_min": 15,
        "skill_tags": ["visibility", "weather", "night-operations"],
        "machine_type_relevance": ["EXCAVATOR", "LOADER", "DOZER", "GRADER"],
        "is_required": False,
    },
]
